# Generated by Django 4.1.2 on 2022-10-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categories_models",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoriy",
                    models.CharField(max_length=25, verbose_name="Котегория"),
                ),
                ("photo", models.ImageField(upload_to="categoriy/")),
            ],
            options={
                "verbose_name": "Котегория",
                "verbose_name_plural": "Котегории",
            },
        ),
    ]
