# Generated by Django 4.1 on 2022-12-13 13:42

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ilm_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lesson_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='lesson/')),
                ('name', models.CharField(max_length=50)),
                ('prise', models.IntegerField()),
                ('categoriy_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilm_pages.categories_models')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Moduls_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduls_l', models.CharField(max_length=100)),
                ('lesson_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilm_pages.lesson_models')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
            },
        ),
        migrations.CreateModel(
            name='thems_video_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
                ('info', models.TextField(default='topilmadi')),
                ('info_url', models.CharField(max_length=100)),
                ('Moduls_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilm_pages.moduls_models')),
            ],
            options={
                'verbose_name': 'Урок-видео',
                'verbose_name_plural': 'Уроки-видео',
            },
        ),
        migrations.CreateModel(
            name='Techer_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50)),
                ('techer_p', models.ImageField(upload_to='teachers/')),
                ('teacher_info', models.TextField()),
                ('categoriy_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilm_pages.categories_models')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
        ),
        migrations.AddField(
            model_name='lesson_models',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilm_pages.techer_models'),
        ),
    ]
